const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),ganache=require('ganache'),{ethers}=require('ethers'),{chromium}=require('playwright');
(async()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../../output/selection/deploy/deployment-config.js'),'utf8'),ctx);const cfg=ctx.window.RESONANCE_DEPLOYMENT,rpc=ganache.provider({chain:{chainId:11155111},logging:{quiet:true}}),ep=new ethers.BrowserProvider(rpc);ep.pollingInterval=10;const signer=await ep.getSigner(),a=await signer.getAddress(),other=await(await ep.getSigner(1)).getAddress();const r=await(await signer.sendTransaction({data:cfg.creationData})).wait(),c=new ethers.Contract(r.contractAddress,cfg.abi,signer);const b=await chromium.launch({channel:'chrome',headless:true}),p=await b.newPage();let chain='0xaa36a7';const requests=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await p.exposeFunction('gateRPC',async args=>{requests.push(args.method);if(args.method==='eth_chainId')return chain;if(args.method==='eth_requestAccounts')args={method:'eth_accounts'};return rpc.request(args);});await p.addInitScript(config=>{Object.defineProperty(window,'RESONANCE_MINT',{get:()=>config,set:()=>{}});window.handlers={};window.ethereum={isRabby:true,request:a=>window.gateRPC(a),on:(e,f)=>window.handlers[e]=f,removeListener(){}};},{...JSON.parse(JSON.stringify(cfg)),address:r.contractAddress});
await p.goto('file://'+path.resolve(__dirname,'../../output/selection/vault/scheduled.html'));
await p.click('#gate-connect');await p.waitForFunction(()=>!document.querySelector('#gate-refresh').disabled);assert(await p.locator('#enter-demo').isDisabled());
await(await c.claim(0)).wait();await p.click('#gate-refresh');await p.waitForFunction(()=>!document.querySelector('#gate-refresh').disabled);assert(await p.locator('#enter-demo').isDisabled());
await(await c.claim(2)).wait();await p.click('#gate-refresh');await p.waitForFunction(()=>!document.querySelector('#enter-demo').disabled);await p.click('#enter-demo');await p.waitForSelector('#workspace:visible');
async function review(){await p.click('#review');await p.waitForSelector('#review-box:visible');await p.click('#confirm');await p.waitForFunction(()=>document.querySelector('#state').textContent==='RUNNING');}
async function tick(n){for(let i=0;i<n;i++){const before=await p.locator('#step').textContent();await p.click('#advance');await p.waitForFunction(prev=>document.querySelector('#step').textContent!==prev,before);}}
await review();assert.equal(await p.locator('#reserved').textContent(),'20.00');await tick(4);assert.equal(await p.locator('#state').textContent(),'FINISHED');assert.equal(await p.locator('#spent').textContent(),'20.00');assert.equal(await p.locator('#owned').textContent(),'2.4750');
await review();await p.click('#pause');await p.waitForFunction(()=>document.querySelector('#state').textContent==='PAUSED');await tick(2);assert.match(await p.locator('#results').textContent(),/1 skipped/);await p.click('#pause');await p.waitForFunction(()=>document.querySelector('#state').textContent==='RUNNING');await tick(2);assert.equal(await p.locator('#spent').textContent(),'30.00');
await review();await(await c.transferFrom(a,other,2)).wait();await p.click('#gate-refresh');await p.waitForFunction(()=>document.querySelector('#workspace').hidden);assert.equal(await p.locator('#reserved').textContent(),'0.00');assert.equal(await p.locator('#state').textContent(),'CANCELLED');assert.equal(await p.locator('#available').textContent(),'70.00');
await(await c.connect(await ep.getSigner(1)).transferFrom(other,a,2)).wait();await p.click('#gate-refresh');await p.waitForFunction(()=>!document.querySelector('#enter-demo').disabled);await p.click('#enter-demo');await p.waitForSelector('#workspace:visible');
await p.click('#review');await p.waitForSelector('#review-box:visible');chain='0x1';await p.evaluate(()=>window.handlers.chainChanged('0x1'));assert(await p.locator('#workspace').isHidden());assert(await p.locator('#review-box').isHidden());
assert(!requests.some(m=>/sendTransaction|sign|personal/.test(m)));await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await b.close();await rpc.disconnect();console.log('PASS Eric: Diren NFT rejected, Eric NFT unlock, scheduled buys, pause skip, ownership loss refund, review invalidation, read-only wallet calls, mobile.');})().catch(e=>{console.error(e);process.exit(1)});
